### ISSUE TITLE
TODO List:

### ISSUE THREAD

**Issue by fbogetti0012** [Vallauri/inf5aprogetto-fbogetti0012#1]
* [ ] Download of Technologies for the project
* [ ] Configuration of SMTP Server, IMAP, POP3
* [ ] Testing SMTP Server and PHPMailer
* [ ] Testing openpgp.js lib to encrypt and decrypt the email content.

**Comment by fbogetti0012** [comment]
![no-response](https://user-images.githubusercontent.com/62405569/77226060-87170580-6b75-11ea-9cfe-e7459658f895.png)

```bash
inet_interfaces = all
inet_protocols = ipv4
```
Even though the `postfix` service is running, i can't reach port 25. 
Unable to spot the configuration error.
